packages:
  - "packages/*"
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
overrides:
  "react": "npm:@preact/compat@latest"
  "react-dom": "npm:@preact/compat@latest"
