/**
 * @file Build script that generates react components from svg icon files
 * @author Max Caplan <contact@maxcaplan.com>
 */

import fs from "node:fs/promises";
import { type ParsedPath, default as path } from "node:path";

import DOMPurify from "isomorphic-dompurify";

//
// Constants
//

const DEFAULT_SOURCE_DIR = "icons";
const DEFAULT_OUT_DIR = path.join("src", "generated");

const DEFAULT_ICON_STYLES = ["regular", "fill"];
const DEFAULT_IGNORE_FILTERS = ["TEMPLATE.svg"];

const GENERATED_FILE_HEADER =
  "/** This file is automatically generated. Do not edit */";

const LOG_PREFIX = "\x1b[34m[generate:icons]\x1b[0m";

//
// Types
//

interface IconStyleMeta {
  path: string;
}

type IconStyleData = IconStyleMeta & { view_box?: string; inner_html: string };

interface IconMeta {
  name: string;
  styles: Record<string, IconStyleMeta>;
}

type IconData = IconMeta & {
  styles: Record<string, IconStyleData>;
};

type IconDataMap = Record<string, IconData>;

//
// Functions
//

/** Create a camalcase name from icon path info */
function createIconName(icon_path_info: ParsedPath): string {
  return icon_path_info.name
    .replace(/[_ ]/g, "-")
    .split("-")
    .map(
      (name_component) =>
        name_component.charAt(0).toUpperCase() + name_component.slice(1),
    )
    .join("");
}

/** Get path info for svg icon files in a given directory */
async function getDirIconPathInfo(
  dir_path: string,
  ignore_filters: string[] = [],
): Promise<ParsedPath[]> {
  let file_basenames: string[] = [];

  try {
    file_basenames = await fs.readdir(dir_path);

    return Promise.all(
      file_basenames.map(async (basename) => {
        try {
          const file_stats = await fs.stat(path.join(dir_path, basename));

          return (
            basename.endsWith(".svg") && // Ensure file is an svg
            !ignore_filters.includes(basename) && // Ensure file is not in ignore filters
            file_stats.isFile() // Ensure file is not a dir
          );
        } catch (e) {
          console.warn(
            `Skipping icon file ${path.join(dir_path, basename)}:`,
            e,
          );
          return false;
        }
      }),
    ).then(
      (results) =>
        file_basenames
          .filter((_v, index) => results[index]) // Remove skipped files
          .map((basename) => path.parse(path.join(dir_path, basename))), // Parse file paths
    );
  } catch (e) {
    console.error(`Failed to get icon directory data for ${dir_path}:`, e);
    return [];
  }
}

/** Get svg data for an icon path */
async function getIconData(
  icon_path: string,
): Promise<{ view_box?: string; inner_html: string }> {
  // Read file
  const contents = await fs.readFile(icon_path, { encoding: "utf8" });

  // Ensure all contents of `defs` elements are removed
  DOMPurify.addHook("uponSanitizeElement", (node, data) => {
    if (data.tagName === "defs") {
      return node.parentNode?.removeChild(node);
    }
  });

  // Sanitize icon svg file
  const clean_data = DOMPurify.sanitize(contents, {
    ALLOWED_TAGS: ["svg", "path"],
    ALLOWED_ATTR: ["viewBox", "xmlns", "d"],
    RETURN_DOM_FRAGMENT: true,
  }).firstElementChild;

  // Ensure data is an svg element
  if (clean_data === null || clean_data.nodeName !== "svg") {
    throw new Error(`${icon_path} is not a valid svg`);
  }

  const inner_html = clean_data.innerHTML.trim().replace(/\>[\s]+\</gm, "><");
  const view_box = clean_data.getAttribute("viewBox") ?? undefined;

  return { view_box, inner_html };
}

/** Map icon styles based on file name */
async function createIconDataMap(
  icon_paths: ParsedPath[],
): Promise<IconDataMap> {
  // Create map of icon meta data
  const icon_meta_map = icon_paths.reduce<Record<string, IconMeta>>(
    (icon_map, icon_path_info) => {
      const style_name = path.parse(icon_path_info.dir).base;
      const icon_path = path.join(icon_path_info.dir, icon_path_info.base);

      if (icon_map[icon_path_info.name] === undefined) {
        // Add new icon to map
        icon_map[icon_path_info.name] = {
          name: createIconName(icon_path_info),
          styles: {
            [style_name]: {
              path: icon_path,
            },
          },
        };
      } else if (
        icon_map[icon_path_info.name].styles[style_name] === undefined
      ) {
        // Add style to existing icon in map
        icon_map[icon_path_info.name].styles[style_name] = {
          path: icon_path,
        };
      } else {
        console.warn(`Skipping duplicate icon style ${icon_path}`);
      }

      return icon_map;
    },
    {},
  );

  // Get data for icon meta data map
  return Promise.all(
    Object.entries(icon_meta_map).map<Promise<[string, IconData]>>(
      async ([icon_key, icon_meta]) => {
        // Get data for each icon style
        const style_data = await Promise.all(
          Object.entries(icon_meta.styles).map<
            Promise<[string, IconStyleData]>
          >(async ([style_key, style_meta]) => [
            style_key,
            {
              ...style_meta,
              ...(await getIconData(style_meta.path)),
            },
          ]),
        ).then((results) => Object.fromEntries(results));

        return [icon_key, { ...icon_meta, styles: style_data }];
      },
    ),
  ).then((results) => Object.fromEntries(results));
}

/** Generate source string for icon component from icon data */
function generateIconComponentSource(
  icon_key: string,
  icon_data: IconData,
): string {
  const icon_styles = Object.entries(icon_data.styles);

  // Ensure icon has style data
  if (icon_styles.length <= 0) {
    throw new Error(`Icon "${icon_data.name}" has no styles`);
  }

  const createRootComponentSource = (view_box?: string) => {
    const attributes = [
      view_box ? `viewBox="${view_box}"` : undefined,
      'xmlns="https://www.w3.org/2000/svg"',
    ]
      .filter((v) => !!v)
      .join(" ");

    return `(props) => <svg ${attributes} {...props} />`;
  };

  const style_map_source = icon_styles
    .map(([style_key, style_data]) => {
      return (
        `\t\t"${style_key}": {\n` +
        `\t\t\troot: ${createRootComponentSource(style_data.view_box)},\n` +
        `\t\t\tcontent: ${style_data.inner_html},\n\t\t},`
      );
    })
    .join("\n");

  return (
    `${GENERATED_FILE_HEADER}\n\n` +
    'import { createIconComponent } from "../../components/Icon";\n\n' +
    `export const ${icon_data.name} = createIconComponent("${icon_key}",\n` +
    `\t{\n${style_map_source}\n\t},\n` +
    ");"
  );
}

/** Generate source string for icon components index file */
function generateIconsIndexSource(icon_data_map: IconDataMap): string {
  const component_imports = Object.entries(icon_data_map)
    .map(
      ([icon_key, icon_data]) =>
        `import { ${icon_data.name} } from "./${icon_key}";`,
    )
    .join("\n");

  const component_exports = `export {\n\t${Object.values(icon_data_map)
    .map((icon_data) => icon_data.name)
    .join(",\n\t")}\n};`;

  const icon_map_export = `export const icons = {\n\t${Object.entries(
    icon_data_map,
  )
    .map(([icon_key, icon_data]) => `"${icon_key}": ${icon_data.name},`)
    .join("\n\t")}\n};`;

  const names_export = `export const icon_names = [\n\t${Object.keys(
    icon_data_map,
  )
    .map((icon_key) => `"${icon_key}"`)
    .join(",\n\t")}\n] as const;`;

  const names_type_export = `export type IconName = (typeof icon_names)[number];`;

  const styles_type_export = `export type IconStyle = ${Object.values(
    icon_data_map,
  )
    .reduce<string[]>((styles, icon_data) => {
      Object.keys(icon_data.styles).forEach((style_key) => {
        if (!styles.includes(style_key)) {
          styles.push(style_key);
        }
      });
      return styles;
    }, [])
    .map((style) => `"${style}"`)
    .join(" | ")};`;

  return (
    `${GENERATED_FILE_HEADER}\n\n` +
    `${component_imports}\n\n` +
    `${names_export}\n\n` +
    `${names_type_export}\n` +
    `${styles_type_export}\n\n` +
    `${icon_map_export}\n\n` +
    `${component_exports}`
  );
}

function infolog(...data: any[]) {
  console.info(LOG_PREFIX, ...data);
}

/** Main script function */
async function main() {
  const time_label = `${LOG_PREFIX} Generated in`;
  console.time(time_label);

  const source_dir = DEFAULT_SOURCE_DIR;
  const out_dir = DEFAULT_OUT_DIR;
  const components_dir = path.join(out_dir, "icons");
  const icon_dirs = DEFAULT_ICON_STYLES;
  const ignore_filters = DEFAULT_IGNORE_FILTERS;

  infolog("Getting icon paths");

  // Get path info for icons in all icon dirs
  const icon_paths = (
    await Promise.all(
      icon_dirs.map((dir) =>
        getDirIconPathInfo(path.join(source_dir, dir), ignore_filters),
      ),
    )
  ).flat();

  infolog("Loading icon data");

  // Create map of icon data
  let icon_data_map = await createIconDataMap(icon_paths);

  // Parse icon data map stats
  const load_stats = Object.values(icon_data_map).reduce<
    Record<string, number>
  >((stats, icon_data) => {
    Object.keys(icon_data.styles).forEach((style_key) => {
      if (stats[style_key] === undefined) {
        stats[style_key] = 1;
      } else {
        stats[style_key] += 1;
      }
    });

    return stats;
  }, {});

  infolog("Icon data loaded:", load_stats);

  // Clean out dir
  try {
    await fs.stat(components_dir);
    await fs.rm(components_dir, { recursive: true, force: true });
  } catch (_e) {}

  // Create out dir
  await fs.mkdir(components_dir, { recursive: true });

  infolog("Generating component files");

  // Write icon components to file
  const generated_components_count = await Promise.all(
    Object.entries(icon_data_map).map(async ([icon_key, icon_data]) => {
      await fs.writeFile(
        path.join(components_dir, `${icon_key}.tsx`),
        generateIconComponentSource(icon_key, icon_data),
        {
          encoding: "utf8",
          flag: "w+",
        },
      );

      return true;
    }),
  ).then((results) => results.filter((ok) => ok).length);

  infolog(`Generated ${generated_components_count} component(s)`);

  infolog(
    `Generating components index file "${path.join(components_dir, "index.ts")}"`,
  );

  // Write icon components index to file
  await fs.writeFile(
    path.join(components_dir, "index.ts"),
    generateIconsIndexSource(icon_data_map),
    {
      encoding: "utf8",
      flag: "w+",
    },
  );

  console.timeEnd(time_label);
}

// Run script
main();
